### ISSUE TITLE
Build fails on OSX

### ISSUE THREAD

**Issue by Fohlen** [inexor-game/conan-grpc#7]
I have tried `conan install grpc/1.17.2@inexorgame/stable` on OSX and it crashes with the following message

```
grpc/1.17.2@inexorgame/stable: Trying with 'inexor'...
Downloading conanmanifest.txt
[==================================================] 166B/166B
Downloading conanfile.py
[==================================================] 5.7KB/5.7KB
Downloading conan_export.tgz
[==================================================] 788B/788B
Decompressing conan_export.tgz: 100%|██████████| 788/788 [00:00<00:00, 172kB/s]
Traceback (most recent call last):
  File "/usr/local/Cellar/conan/1.11.1/libexec/lib/python3.7/site-packages/conans/client/command.py", line 1427, in run
    method(args[0][1:])
  File "/usr/local/Cellar/conan/1.11.1/libexec/lib/python3.7/site-packages/conans/client/command.py", line 393, in install
    install_folder=args.install_folder)
  File "/usr/local/Cellar/conan/1.11.1/libexec/lib/python3.7/site-packages/conans/client/conan_api.py", line 87, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/Cellar/conan/1.11.1/libexec/lib/python3.7/site-packages/conans/client/conan_api.py", line 484, in install_reference
    generators=generators)
  File "/usr/local/Cellar/conan/1.11.1/libexec/lib/python3.7/site-packages/conans/client/manager.py", line 76, in install
    self._recorder, None)
  File "/usr/local/Cellar/conan/1.11.1/libexec/lib/python3.7/site-packages/conans/client/graph/graph_manager.py", line 141, in load_graph
    processed_profile=processed_profile)
  File "/usr/local/Cellar/conan/1.11.1/libexec/lib/python3.7/site-packages/conans/client/graph/graph_manager.py", line 229, in _load_graph
    binaries_analyzer.evaluate_graph(graph, build_mode, update, remote_name)
  File "/usr/local/Cellar/conan/1.11.1/libexec/lib/python3.7/site-packages/conans/client/graph/graph_binaries.py", line 175, in evaluate_graph
    self._evaluate_node(node, build_mode, update, evaluated_references, remote_name)
  File "/usr/local/Cellar/conan/1.11.1/libexec/lib/python3.7/site-packages/conans/client/graph/graph_binaries.py", line 102, in _evaluate_node
    remote = self._registry.prefs.get(package_ref) or self._registry.refs.get(conan_ref)
  File "/usr/local/Cellar/conan/1.11.1/libexec/lib/python3.7/site-packages/conans/client/remote_registry.py", line 122, in get
    return Remote(remote_name, remotes[remote_name][0], remotes[remote_name][1])
KeyError: 'inexorgame'

ERROR: 'inexorgame'
```

**Comment by Croydon** [comment]
Please post the output of

`cmake --version`
`conan --version`
`conan profile show default`


also which macOS version do you use?

**Comment by Fohlen** [comment]
```
cmake version 3.13.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

```
Conan version 1.11.1
```

```
Configuration for profile default:

[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=10.0
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]
```

**Comment by rdewaele** [comment]
```
~❯ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.14.4 (18E226)
      Kernel Version: Darwin 18.5.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: <snip>
      User Name: <snip>
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 16 days 12:30
```

```
~❯ cmake --version
cmake version 3.11.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

```
~❯ conan --version
Conan version 1.14.3
```

```
~❯ conan profile show default
Configuration for profile default:

[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=10.0
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]
```
both
```
conan install grpc/1.17.2@inexorgame/stable
```
and
```
conan install grpc/1.17.2@inexorgame/stable --build
```
worked for me

So it seems that either an update to conan fixed the issue, or something not listed in the output is different.

One thing that grabs my attention is that the actual error (python KeyError) stipulates that the key mentioned (`inexorgame`) was not in the dictionary. This seems to suggest that the error is most likely with conan and not this package specifically.

@Fohlen Have you retried installing the package since your original post, perhaps with an updated conan? Maybe removing & adding the inexorgame remote could help?

**Comment by almcr** [comment]
```
cmake version: 3.14
```

```
[settings]
arch=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=8.1
os=Macos (10.14.1)
```
```
conan version 1.15.0
```

when i try the 1.20 recipe i got this message:
```
Downloading conanmanifest.txt
[==================================================] 166B/166B        
Downloading conanfile.py
[==================================================] 6.0KB/6.0KB      
Downloading conan_export.tgz
[==================================================] 788B/788B        
Decompressing conan_export.tgz: 100%|██████████| 788/788 [00:00<00:00, 379kB/s]
grpc/1.20.0@inexorgame/stable: Downloaded recipe revision 0
OpenSSL/1.0.2r@conan/stable: Not found in local cache, looking in remotes...
OpenSSL/1.0.2r@conan/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt
[==================================================] 120B/120B        
Downloading conanfile.py
[==================================================] 19.1KB/19.1KB    
OpenSSL/1.0.2r@conan/stable: Downloaded recipe revision 0
protobuf/3.6.1@bincrafters/stable: Not found in local cache, looking in remotes...
protobuf/3.6.1@bincrafters/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt
[==================================================] 229B/229B        
Downloading conanfile.py
[==================================================] 3.7KB/3.7KB      
Downloading conan_export.tgz
[==================================================] 760B/760B        
Decompressing conan_export.tgz: 100%|██████████| 760/760 [00:00<00:00, 413kB/s]
protobuf/3.6.1@bincrafters/stable: Downloaded recipe revision 0
protoc_installer/3.6.1@bincrafters/stable: Not found in local cache, looking in remotes...
protoc_installer/3.6.1@bincrafters/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt
[==================================================] 229B/229B        
Downloading conanfile.py
[==================================================] 2.5KB/2.5KB      
Downloading conan_export.tgz
[==================================================] 760B/760B        
Decompressing conan_export.tgz: 100%|██████████| 760/760 [00:00<00:00, 505kB/s]
protoc_installer/3.6.1@bincrafters/stable: Downloaded recipe revision 0

ERROR: ~/.conan/data/protoc_installer/3.6.1/bincrafters/stable/export/conanfile.py: Error while initializing settings. 'settings.os_build' doesn't exist
'settings' possible configurations are ['arch', 'build_type', 'compiler', 'os']
```

**Comment by Croydon** [comment]
@ox2ai this sounds like you have an old settings.yml file without an os_build/arch_build/os_target/arch_target value.

You should have a settings.yml.new file in which you can copy these values and paste them into your settings.yml

Please report back if this is fixing your issue

**Comment by almcr** [comment]
now I have the following after I've defined the corresponding values
```
ERROR: protoc_installer/3.6.1@bincrafters/stable: 'settings.arch_build' value not defined
```

**Comment by peter-moran** [comment]
Your default profile does not list `arch_build`.

**Comment by peter-moran** [comment]
Maybe this ticket should be closed since @rdewaele demonstrated it working?

**Comment by Croydon** [comment]
Agreed
